"""initial_on_chain_schema

Revision ID: 51ea6bb55823
Revises: 
Create Date: 2026-03-05 17:17:42.377510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51ea6bb55823'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('input_cost_usd', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('output_cost_usd', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_events_session_id'), 'llm_usage_events', ['session_id'], unique=False)
    op.create_table('project_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('chain', sa.Enum('HEDERA', 'SOLANA', 'STELLAR', 'ETHEREUM', 'BASE', 'ARBITRUM', 'OTHER', name='chaintype'), nullable=False),
    sa.Column('category', sa.Enum('DEX', 'LENDING', 'YIELD', 'BRIDGE', 'NFT', 'MEMECOIN', 'INFRASTRUCTURE', 'OTHER', name='protocolcategory'), nullable=False),
    sa.Column('audit_status', sa.Enum('AUDITED', 'UNAUDITED', 'PENDING', 'PARTIAL', name='auditstatus'), nullable=False),
    sa.Column('is_open_source', sa.Boolean(), nullable=True),
    sa.Column('admin_key_controlled', sa.Boolean(), nullable=True),
    sa.Column('token_ticker', sa.String(), nullable=True),
    sa.Column('tokenomics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('identified_vulnerabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_profiles_project_name'), 'project_profiles', ['project_name'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('overall_risk_level', sa.Enum('SAFE', 'MODERATE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('flagged_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('positive_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_project_profiles_project_name'), table_name='project_profiles')
    op.drop_table('project_profiles')
    op.drop_index(op.f('ix_llm_usage_events_session_id'), table_name='llm_usage_events')
    op.drop_table('llm_usage_events')
    # ### end Alembic commands ###
