from fpdf import FPDF
from datetime import datetime
from app.models import RiskLevel, ProjectProfile, RiskAssessment

class SecurityReportPDF(FPDF):
    def header(self):
        # Logo or Title
        self.set_font("Arial", "B", 16)
        self.set_text_color(44, 62, 80)
        self.cell(0, 10, "On-Chain Fundamentals & Risk Assessment", 0, 1, "C")
        self.set_font("Arial", "I", 10)
        self.cell(0, 5, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1, "C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(127, 140, 141)
        self.cell(0, 10, f"Page {self.page_no()} | Confidential Security Analysis", 0, 0, "C")

def generate_risk_report(profile: ProjectProfile, assessment: RiskAssessment) -> bytes:
    pdf = SecurityReportPDF()
    pdf.add_page()
    
    # 1. Project Overview
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(52, 73, 94)
    pdf.cell(0, 10, f"Project: {profile.project_name}", 0, 1)
    
    pdf.set_font("Arial", "", 11)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 7, f"Blockchain: {profile.chain}\nCategory: {profile.category}\nTicker: {profile.token_ticker or 'N/A'}")
    pdf.ln(5)

    # 2. Risk Score (Highlighted)
    score_color = (46, 204, 113) # Safe (Green)
    if assessment.overall_risk_level == RiskLevel.CRITICAL:
        score_color = (231, 76, 60) # Red
    elif assessment.overall_risk_level == RiskLevel.HIGH:
        score_color = (230, 126, 34) # Orange
    elif assessment.overall_risk_level == RiskLevel.MODERATE:
        score_color = (241, 196, 15) # Yellow

    pdf.set_fill_color(*score_color)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, f"OVERALL RISK LEVEL: {assessment.overall_risk_level.value.upper()} ({assessment.risk_score}/100)", 1, 1, "C", fill=True)
    pdf.ln(5)

    # 3. Summary
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Executive Summary", 0, 1)
    pdf.set_font("Arial", "", 10)
    pdf.multi_cell(0, 5, profile.summary or "No summary provided.")
    pdf.ln(5)

    # 4. Flagged Issues
    if assessment.flagged_issues:
        pdf.set_font("Arial", "B", 12)
        pdf.set_text_color(192, 57, 43)
        pdf.cell(0, 10, "Flagged Issues & Vulnerabilities", 0, 1)
        pdf.set_font("Arial", "", 10)
        pdf.set_text_color(0, 0, 0)
        for issue in assessment.flagged_issues:
            pdf.multi_cell(0, 5, f"[-] {issue}")
            pdf.ln(2)
        pdf.ln(5)

    # 5. Positive Signals
    if assessment.positive_signals:
        pdf.set_font("Arial", "B", 12)
        pdf.set_text_color(39, 174, 96)
        pdf.cell(0, 10, "Positive Fundamentals", 0, 1)
        pdf.set_font("Arial", "", 10)
        pdf.set_text_color(0, 0, 0)
        for signal in assessment.positive_signals:
            pdf.multi_cell(0, 5, f"[+] {signal}")
            pdf.ln(2)
        pdf.ln(5)

    # 6. Recommended Action
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Recommended Action", 0, 1)
    pdf.set_font("Arial", "I", 10)
    pdf.multi_cell(0, 5, assessment.recommended_action)

    # Disclaimer
    pdf.ln(10)
    pdf.set_font("Arial", "I", 8)
    pdf.set_text_color(149, 165, 166)
    disclaimer = "DISCLAIMER: This report is generated by an AI-powered security analyzer. It is for informational purposes only and does not constitute financial or legal advice. Smart contract interaction always carries inherent risk. Always conduct your own due diligence (DYOR)."
    pdf.multi_cell(0, 4, disclaimer)

    return pdf.output(dest='S')
